import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Menu } from "~/components/top-bar";

export const metadata = {
  title: "playlistpal",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Menu />
        <section className="items-center bg-gradient-to-l from-[#62d089] to-[#457e59] text-white sm:flex-col lg:h-[calc(100vh-2.25rem)] lg:flex-row">
          {children}
        </section>
      </body>
    </html>
  );
}
